# Matrix Addition

In this exercises, you will write a function that accepts two matrices and outputs their sum. Think about how you could do this with a for loop nested inside another for loop.

In [1]:
import numpy as np

In [3]:
### TODO: Write a function called matrix_addition that 
###     calculate the sum of two matrices
###
### INPUTS:
###    matrix A _ an m x n matrix
###    matrix B _ an m x n matrix
###
### OUPUT:
###   matrixSum _ sum of matrix A + matrix B

def matrix_addition(matrixA, matrixB):

    # initialize matrix to hold the results
    return matrixA + matrixB

### When you run this code cell, your matrix addition function
### will run on the A and B matrix.

A = np.array([
    [2,5,1], 
    [6,9,7.4], 
    [2,1,1], 
    [8,5,3], 
    [2,1,6], 
    [5,3,1]
])

B = np.array([
    [7, 19, 5.1], 
    [6.5,9.2,7.4], 
    [2.8,1.5,12], 
    [8,5,3], 
    [2,1,6], 
    [2,33,1]
])

print(matrix_addition(A, B))

[[ 9.  24.   6.1]
 [12.5 18.2 14.8]
 [ 4.8  2.5 13. ]
 [16.  10.   6. ]
 [ 4.   2.  12. ]
 [ 7.  36.   2. ]]


### Vectors versus Matrices

What happens if you run the cell below? Here you are adding two vectors together. Does your code still work?

In [5]:

print(matrix_addition(np.array([4, 2, 1]), np.array([5, 2, 7])))

[9 4 8]


Why did this error occur? Because your code assumes that a matrix is a two-dimensional grid represented by a list of lists. But a horizontal vector, which can also be considered a matrix, is a one-dimensional grid represented by a single list.

What happens if you store a vector as a list of lists like [[4, 2, 1]] and [[5, 2, 7]]? Does your function work? Run the code cell below to find out.

In [6]:
print(matrix_addition(np.array([[4, 2, 1]]), np.array([[5, 2, 7]])))

[[9 4 8]]


### Test your Code
Run the cell below. If there is no output, then your results are as expected.

In [7]:
assert (matrix_addition(np.array([
    [1, 2, 3]]), 
    np.array([[4, 5, 6]])) == np.array([[5, 7, 9]])).all()

assert (matrix_addition(
    np.array([[4]]), np.array([
    [5]])) == np.array([[9]])).all()

assert (matrix_addition(np.array([[1, 2, 3], 
                        [4, 5, 6]]), 
                       np.array([[7, 8, 9], 
                        [10, 11, 12]])) == np.array([[8, 10, 12], 
                                           [14, 16, 18]])).all()