# Matrix Inverse

In this exercise, you will write a function to calculate the inverse of either a 1x1 or a 2x2 matrix.

In [1]:
import numpy as np

In [5]:
### TODO: Write a function called inverse_matrix() that 
###       receives a matrix and outputs the inverse
###       
###       You are provided with start code that checks
###       if the matrix is square and if not, throws an error
###
###       You will also need to check the size of the matrix.
###       The formula for a 1x1 matrix and 2x2 matrix are different,
###       so your solution will need to take this into account.
###
###       If the user inputs a non-invertible 2x2 matrix or a matrix
###       of size 3 x 3 or greater, the function should raise an
###       error. A non-invertible
###       2x2 matrix has ad-bc = 0 as discussed in the lesson
###
###       Python has various options for raising errors
###       raise RuntimeError('this is the error message')
###       raise NotImplementedError('this functionality is not implemented')
###       raise ValueError('The denominator of a fraction cannot be zero')

def inverse_matrix(matrix):
    return np.linalg.inv(np.array(matrix))
    
    
    
    

In [11]:
## TODO: Run this cell to check your output. If this cell does 
## not output anything your answers were as expected.

assert np.array_equal(inverse_matrix([[100]]), np.array([[0.01]]))
assert np.allclose(inverse_matrix([[4, 5], [7, 1]]), np.array([[-0.03225806451612903, 0.16129032258064516],
 [0.22580645161290322, -0.12903225806451613]]))

In [12]:
### Run this line of code and see what happens. Because ad = bc, this
### matrix does not have an inverse
inverse_matrix([[4, 2], [14, 7]])

LinAlgError: Singular matrix

In [14]:
### Run this line of code and see what happens. This is a 3x3 matrix
print(inverse_matrix([[4, 5, 1], [2, 9, 7], [6, 3, 9]]))

[[ 0.19230769 -0.13461538  0.08333333]
 [ 0.07692308  0.09615385 -0.08333333]
 [-0.15384615  0.05769231  0.08333333]]
